- name: "download kind"
  become: yes
  become_user: root
  get_url:
    url: 'https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-linux-amd64'
    dest: '/usr/local/bin/kind'
    mode: 0755

- name: "Create kind config"
  template:
    src: ./kind-config.yaml.template
    dest: /root/kind-config.yaml
